[package]
name = "day-01-calorie-counting"
version = "0.1.0"
edition = "2024"

[dependencies]
color-eyre.workspace = true
itertools.workspace = true

[dev-dependencies]
rstest.workspace = true

[lints]
workspace = true
